#!/bin/sh

# Copyright (C) 2024 Aoki Kenji
# This file is part of Aoki Kenji's Dotfiles.
#
# Aoki Kenji's Dotfiles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Aoki Kenji's Dotfiles is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# Aoki Kenji's Dotfiles. If not, see <https://www.gnu.org/licenses/>.

if [ -z "$HOME" ]; then
    echo "Failed to get the home directory." >&2
    exit 1
fi

export PATH="${HOME}/.local/bin:${PATH}"

export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-${HOME}/.local/state}"

export XINITRC="${XDG_CONFIG_HOME}/xorg/xinitrc"

mkdir --mode 700 --parents -- \
    "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME" ||
    exit 1

export EDITOR="nvim"

if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
    mkdir --parents -- "${XDG_STATE_HOME}/xorg" || exit 1
    startx "$XINITRC" -- -ardelay 200 -arinterval 20 -keeptty -nolisten tcp \
        > "${XDG_STATE_HOME}/xorg/Xorg.tty.log" 2>&1
    exit "$?"
fi
